In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
%matplotlib inline

In [4]:
lista_dias_del_meses = [31,28,31,30,31,30,31,31,30,31,30,31]

================================================================

<h3> PARTÍCULAS PM 10 </h3>

================================================================

In [117]:
particulasPM10 = pd.DataFrame()
totales = []



    

for x in range(2001,2017):
    
    df = pd.read_excel('datos/PM_10/PM10_DD_'+str(x)+'.xlsx', sep=";")
    df_ordenado_por_meses= df.sort_values(by=['MES'])
    # Nos interesa únicamente las mediciones diarias por meses de todas las estaciones, para poder sacar 
    # el valor mensual del contaminante:
    df_datos_diarios_por_mes = df_ordenado_por_meses.iloc[:,6:]
   
    
    totales = []

    for p in range(1,13):
        
        medias_por_dia_mes = df_datos_diarios_por_mes[df_datos_diarios_por_mes['MES']== p ].iloc[:,1:].mean()
        media_por_mes = medias_por_dia_mes.mean()   
        totales.append(media_por_mes)
    serie1 = pd.Series(totales)
    
    particulasPM10['y'+str(x)] = serie1

In [118]:
particulasPM10

,y2001,y2002,y2003,y2004,y2005,y2006,y2007,y2008,y2009,y2010,y2011,y2012,y2013,y2014,y2015,y2016
0,47.293600,36.878094,24.812479,22.208213,27.465788,26.103168,36.270203,32.937238,18.927775,17.405147,25.596995,23.290370,18.221588,17.171058,20.498432,20.215709
1,55.128328,37.373950,25.993710,35.577635,29.242306,36.802329,29.698028,34.648043,25.483145,17.633227,26.295154,25.647738,17.103671,15.746431,18.960200,22.846952
2,32.606092,35.112357,38.067317,34.543537,40.497777,30.786894,29.645428,23.341674,28.733972,27.876883,21.305298,27.947710,16.154088,23.448508,21.428050,16.490487
3,28.833526,34.246774,29.736321,21.621801,32.012189,31.027896,30.702033,24.673716,19.232946,21.625204,24.652417,15.694662,18.254282,17.973531,20.854529,14.965678
4,31.295070,29.014845,30.096026,26.338370,34.735496,36.667626,30.537968,23.252266,28.558337,18.860221,20.999829,20.008141,16.831030,16.643651,21.844693,16.677103
5,32.786156,35.952304,39.753812,31.735655,38.475431,42.832881,27.853268,23.137711,25.661903,19.830960,19.593463,25.043164,20.632805,20.222209,20.558683,19.827451
6,30.895709,34.648614,33.494597,35.769257,35.124545,36.123316,31.530919,25.680810,25.631606,24.248480,21.316974,22.512195,23.621117,18.617661,25.231784,22.514125
7,31.055727,27.835951,33.645129,26.395983,29.128529,25.221841,29.695401,23.163241,23.567161,21.536846,23.102519,25.770377,21.252798,18.686920,20.670335,21.615365
8,29.503108,29.498977,27.977213,33.642223,29.504051,28.287671,29.153729,24.710823,22.742673,20.094987,21.991548,21.197685,20.630053,20.689025,17.744804,19.828938
9,31.723759,29.704568,21.944123,28.332649,26.643167,32.302350,26.472275,31.154252,23.445264,21.018377,24.441703,19.592631,20.032676,24.765134,19.242708,22.152234
10,28.172920,27.085234,28.220019,32.961873,22.349679,31.329759,38.893394,20.182580,27.309348,17.926363,19.247261,17.639701,16.972349,23.278579,22.327421,18.917833
11,30.501191,26.863580,22.810386,20.650977,25.690856,25.795844,28.287442,20.829772,17.708222,20.538174,17.943079,18.384498,23.007033,17.879183,34.644828,18.779441

In [136]:
seriePm10 = pd.Series()

for j in range(2001,2017):
        
    seriePm10 = seriePm10.append(pd.Series(particulasPM10['y'+str(j)]))
    print(particulasPM10['y'+str(j)])

0     47.293600
1     55.128328
2     32.606092
3     28.833526
4     31.295070
5     32.786156
6     30.895709
7     31.055727
8     29.503108
9     31.723759
10    28.172920
11    30.501191
Name: y2001, dtype: float64
0     36.878094
1     37.373950
2     35.112357
3     34.246774
4     29.014845
5     35.952304
6     34.648614
7     27.835951
8     29.498977
9     29.704568
10    27.085234
11    26.863580
Name: y2002, dtype: float64
0     24.812479
1     25.993710
2     38.067317
3     29.736321
4     30.096026
5     39.753812
6     33.494597
7     33.645129
8     27.977213
9     21.944123
10    28.220019
11    22.810386
Name: y2003, dtype: float64
0     22.208213
1     35.577635
2     34.543537
3     21.621801
4     26.338370
5     31.735655
6     35.769257
7     26.395983
8     33.642223
9     28.332649
10    32.961873
11    20.650977
Name: y2004, dtype: float64
0     27.465788
1     29.242306
2     40.497777
3     32.012189
4     34.735496
5     38.475431
6     35.124545
7     29.128529
8     29.504051
9     26.643167
10    22.349679
11    25.690856
Name: y2005, dtype: float64
0     26.103168
1     36.802329
2     30.786894
3     31.027896
4     36.667626
5     42.832881
6     36.123316
7     25.221841
8     28.287671
9     32.302350
10    31.329759
11    25.795844
Name: y2006, dtype: float64
0     36.270203
1     29.698028
2     29.645428
3     30.702033
4     30.537968
5     27.853268
6     31.530919
7     29.695401
8     29.153729
9     26.472275
10    38.893394
11    28.287442
Name: y2007, dtype: float64
0     32.937238
1     34.648043
2     23.341674
3     24.673716
4     23.252266
5     23.137711
6     25.680810
7     23.163241
8     24.710823
9     31.154252
10    20.182580
11    20.829772
Name: y2008, dtype: float64
0     18.927775
1     25.483145
2     28.733972
3     19.232946
4     28.558337
5     25.661903
6     25.631606
7     23.567161
8     22.742673
9     23.445264
10    27.309348
11    17.708222
Name: y2009, dtype: float64
0     17.405147
1     17.633227
2     27.876883
3     21.625204
4     18.860221
5     19.830960
6     24.248480
7     21.536846
8     20.094987
9     21.018377
10    17.926363
11    20.538174
Name: y2010, dtype: float64
0     25.596995
1     26.295154
2     21.305298
3     24.652417
4     20.999829
5     19.593463
6     21.316974
7     23.102519
8     21.991548
9     24.441703
10    19.247261
11    17.943079
Name: y2011, dtype: float64
0     23.290370
1     25.647738
2     27.947710
3     15.694662
4     20.008141
5     25.043164
6     22.512195
7     25.770377
8     21.197685
9     19.592631
10    17.639701
11    18.384498
Name: y2012, dtype: float64
0     18.221588
1     17.103671
2     16.154088
3     18.254282
4     16.831030
5     20.632805
6     23.621117
7     21.252798
8     20.630053
9     20.032676
10    16.972349
11    23.007033
Name: y2013, dtype: float64
0     17.171058
1     15.746431
2     23.448508
3     17.973531
4     16.643651
5     20.222209
6     18.617661
7     18.686920
8     20.689025
9     24.765134
10    23.278579
11    17.879183
Name: y2014, dtype: float64
0     20.498432
1     18.960200
2     21.428050
3     20.854529
4     21.844693
5     20.558683
6     25.231784
7     20.670335
8     17.744804
9     19.242708
10    22.327421
11    34.644828
Name: y2015, dtype: float64
0     20.215709
1     22.846952
2     16.490487
3     14.965678
4     16.677103
5     19.827451
6     22.514125
7     21.615365
8     19.828938
9     22.152234
10    18.917833
11    18.779441
Name: y2016, dtype: float64

In [137]:
seriePm10

0     47.293600
1     55.128328
2     32.606092
3     28.833526
4     31.295070
5     32.786156
6     30.895709
7     31.055727
8     29.503108
9     31.723759
10    28.172920
11    30.501191
0     36.878094
1     37.373950
2     35.112357
3     34.246774
4     29.014845
5     35.952304
6     34.648614
7     27.835951
8     29.498977
9     29.704568
10    27.085234
11    26.863580
0     24.812479
1     25.993710
2     38.067317
3     29.736321
4     30.096026
5     39.753812
        ...
6     18.617661
7     18.686920
8     20.689025
9     24.765134
10    23.278579
11    17.879183
0     20.498432
1     18.960200
2     21.428050
3     20.854529
4     21.844693
5     20.558683
6     25.231784
7     20.670335
8     17.744804
9     19.242708
10    22.327421
11    34.644828
0     20.215709
1     22.846952
2     16.490487
3     14.965678
4     16.677103
5     19.827451
6     22.514125
7     21.615365
8     19.828938
9     22.152234
10    18.917833
11    18.779441
Length: 192, dtype: float64

================================================================

<h3> BENZOPIRENOS </h3>

================================================================

In [138]:
benzopirenos = pd.DataFrame()
totales_benzo = []


    

for x in range(2008,2017):
    
    df = pd.read_excel('datos/BENZOPIRENOS/benzopireno'+str(x)+'.xlsx', sep=";")
    df_ordenado_por_meses= df.sort_values(by=['MES'])
    # Nos interesa únicamente las mediciones diarias por meses de todas las estaciones, para poder sacar 
    # el valor mensual del contaminante:
    df_datos_diarios_por_mes = df_ordenado_por_meses.iloc[:,6:]
   
    
    totales_benzo = []

    for p in range(1,13):
        
        medias_por_dia_mes = df_datos_diarios_por_mes[df_datos_diarios_por_mes['MES']== p ].iloc[:,1:].mean()
        media_por_mes = medias_por_dia_mes.mean()   
        totales_benzo.append(media_por_mes)
    serie1 = pd.Series(totales_benzo)
    
    benzopirenos['y'+str(x)] = serie1

In [139]:
benzopirenos

,y2008,y2009,y2010,y2011,y2012,y2013,y2014,y2015,y2016
0,0.281087,0.166132,0.298696,0.338045,0.376155,0.324625,0.328150,0.429181,0.304314
1,0.215056,0.167199,0.256407,0.233718,0.283157,0.320554,0.159172,0.228880,0.216307
2,0.120814,0.116840,0.157722,0.123698,0.145749,0.120355,0.118629,0.122655,0.131191
3,0.073814,0.096300,0.100617,0.067127,0.078653,0.081658,0.081245,0.071921,0.132232
4,0.063008,0.057523,0.071513,0.064411,0.077773,0.072298,0.073954,0.061299,0.141213
5,0.074592,0.057456,0.067540,0.059992,0.073277,0.079319,0.072679,0.063721,0.101415
6,0.073219,0.056686,0.056475,0.060126,0.068019,0.584813,0.066948,0.080654,0.135129
7,0.058027,0.055666,0.062365,0.051317,0.070605,0.067683,0.064383,0.075889,0.093774
8,0.067435,0.063088,0.077519,0.071374,0.072345,0.077402,0.115650,0.067901,0.141517
9,0.137085,0.113399,0.141535,0.111641,0.102420,0.217555,0.121434,0.099616,0.179656
10,0.241857,0.182280,0.243834,0.198960,0.215338,0.208794,0.226795,0.288069,0.363034
11,0.390187,0.147116,0.434916,0.326662,0.305681,0.475331,0.462924,0.584241,0.581631

In [141]:
serieBenzopirenos= pd.Series()

for j in range(2008,2017):
        
    serieBenzopirenos = serieBenzopirenos.append(pd.Series(benzopirenos['y'+str(j)]))

serieBenzopirenos

0     0.281087
1     0.215056
2     0.120814
3     0.073814
4     0.063008
5     0.074592
6     0.073219
7     0.058027
8     0.067435
9     0.137085
10    0.241857
11    0.390187
0     0.166132
1     0.167199
2     0.116840
3     0.096300
4     0.057523
5     0.057456
6     0.056686
7     0.055666
8     0.063088
9     0.113399
10    0.182280
11    0.147116
0     0.298696
1     0.256407
2     0.157722
3     0.100617
4     0.071513
5     0.067540
        ...
6     0.066948
7     0.064383
8     0.115650
9     0.121434
10    0.226795
11    0.462924
0     0.429181
1     0.228880
2     0.122655
3     0.071921
4     0.061299
5     0.063721
6     0.080654
7     0.075889
8     0.067901
9     0.099616
10    0.288069
11    0.584241
0     0.304314
1     0.216307
2     0.131191
3     0.132232
4     0.141213
5     0.101415
6     0.135129
7     0.093774
8     0.141517
9     0.179656
10    0.363034
11    0.581631
Length: 108, dtype: float64

================================================================

<h3> PARTÍCULAS 2.5 </h3>

================================================================

In [143]:
pm25 = pd.DataFrame()
totales_pm25 = []


    

for x in range(2009,2017):
    
    df = pd.read_excel('datos/PM_2_5/PM2_5_'+str(x)+'.xlsx', sep=";")
    df_ordenado_por_meses= df.sort_values(by=['MES'])
    # Nos interesa únicamente las mediciones diarias por meses de todas las estaciones, para poder sacar 
    # el valor mensual del contaminante:
    df_datos_diarios_por_mes = df_ordenado_por_meses.iloc[:,6:]
   
    
    totales_pm25 = []

    for p in range(1,13):
        
        medias_por_dia_mes = df_datos_diarios_por_mes[df_datos_diarios_por_mes['MES']== p ].iloc[:,1:].mean()
        media_por_mes = medias_por_dia_mes.mean()   
        totales_pm25.append(media_por_mes)
    serie1 = pd.Series(totales_pm25)
    
    pm25['y'+str(x)] = serie1

In [144]:
pm25

,y2009,y2010,y2011,y2012,y2013,y2014,y2015,y2016
0,10.019166,9.627312,16.533783,15.613849,11.834837,10.761071,14.528960,12.585015
1,13.413926,10.459479,17.364894,16.095753,10.991193,8.982626,11.421466,12.138998
2,14.339257,15.788309,12.876882,16.860209,9.124274,13.175032,12.616592,9.973211
3,10.276743,12.786244,14.661859,9.635056,10.107784,10.216726,11.378150,7.935261
4,12.550319,10.715953,12.446747,11.364337,9.117599,9.158577,12.356034,8.874574
5,12.473253,10.672609,11.561033,12.890066,11.209215,11.285622,12.358295,11.167802
6,11.695893,12.860917,11.451728,12.033668,14.054037,10.372030,13.868549,11.993658
7,11.854021,11.280487,12.670336,13.705043,11.435059,10.337978,11.412451,10.806331
8,12.077693,10.231391,12.225491,12.101934,11.295613,12.105204,9.646703,11.026962
9,11.333856,11.177488,13.386428,11.728813,10.406346,13.182116,10.654395,11.806980
10,12.717407,10.282415,11.439384,11.082548,9.765985,11.843911,13.312027,11.280043
11,9.490390,12.724314,12.414808,12.628615,14.438559,11.603126,20.774549,12.661403

In [145]:
seriePM25= pd.Series()

for j in range(2009,2017):
        
    seriePM25 = seriePM25.append(pd.Series(pm25['y'+str(j)]))

seriePM25

0     10.019166
1     13.413926
2     14.339257
3     10.276743
4     12.550319
5     12.473253
6     11.695893
7     11.854021
8     12.077693
9     11.333856
10    12.717407
11     9.490390
0      9.627312
1     10.459479
2     15.788309
3     12.786244
4     10.715953
5     10.672609
6     12.860917
7     11.280487
8     10.231391
9     11.177488
10    10.282415
11    12.724314
0     16.533783
1     17.364894
2     12.876882
3     14.661859
4     12.446747
5     11.561033
        ...
6     10.372030
7     10.337978
8     12.105204
9     13.182116
10    11.843911
11    11.603126
0     14.528960
1     11.421466
2     12.616592
3     11.378150
4     12.356034
5     12.358295
6     13.868549
7     11.412451
8      9.646703
9     10.654395
10    13.312027
11    20.774549
0     12.585015
1     12.138998
2      9.973211
3      7.935261
4      8.874574
5     11.167802
6     11.993658
7     10.806331
8     11.026962
9     11.806980
10    11.280043
11    12.661403
Length: 96, dtype: float64

================================================================

<h3> ARSÉNICO</h3>

================================================================

In [146]:
arsenico = pd.DataFrame()
totales_as = []


    

for x in range(2008,2017):
    
    df = pd.read_excel('datos/ARSENICO/As_DD_'+str(x)+'.xlsx', sep=";")
    df_ordenado_por_meses= df.sort_values(by=['MES'])
    # Nos interesa únicamente las mediciones diarias por meses de todas las estaciones, para poder sacar 
    # el valor mensual del contaminante:
    df_datos_diarios_por_mes = df_ordenado_por_meses.iloc[:,6:]
   
    
    totales_as = []

    for p in range(1,13):
        
        medias_por_dia_mes = df_datos_diarios_por_mes[df_datos_diarios_por_mes['MES']== p ].iloc[:,1:].mean()
        media_por_mes = medias_por_dia_mes.mean()   
        totales_as.append(media_por_mes)
    serie1 = pd.Series(totales_as)
    
    arsenico['y'+str(x)] = serie1

In [147]:
arsenico

,y2008,y2009,y2010,y2011,y2012,y2013,y2014,y2015,y2016
0,1.445264,1.182590,0.991241,0.972411,0.982089,1.004395,0.666146,0.693145,0.607211
1,1.270137,1.061766,1.143298,0.991985,0.991102,1.308010,0.635351,0.582942,0.598727
2,1.093210,1.178371,1.086381,0.893003,1.083395,1.711879,0.757959,0.781716,0.584830
3,1.265506,0.836467,1.043513,0.798104,0.859820,0.807379,0.696055,0.627840,0.629344
4,1.218206,0.862348,0.853448,0.823411,0.941410,1.049278,0.632861,0.628041,0.598050
5,1.302040,1.014719,0.970266,1.128078,1.272288,0.898569,0.675564,0.595944,0.690355
6,1.132523,0.945615,0.990888,1.078082,0.953695,0.762031,0.646071,0.603521,0.767258
7,1.175340,0.889275,0.676997,1.046414,1.110710,0.875625,0.580913,0.673715,0.654089
8,0.987349,1.086027,0.896020,1.207515,1.015148,2.304110,0.634101,0.709576,0.666234
9,1.089588,1.169211,1.015055,1.186505,1.015388,0.752148,0.730665,0.643659,0.730070
10,0.897953,1.204066,0.911411,1.227376,0.895233,1.042350,0.697074,0.697220,0.632060
11,0.978699,1.008233,1.100444,0.867254,0.789536,2.320049,0.695029,0.698129,0.686320

In [149]:
serieArsenico= pd.Series()

for j in range(2008,2017):
        
    serieArsenico = serieArsenico.append(pd.Series(arsenico['y'+str(j)]))

serieArsenico

0     1.445264
1     1.270137
2     1.093210
3     1.265506
4     1.218206
5     1.302040
6     1.132523
7     1.175340
8     0.987349
9     1.089588
10    0.897953
11    0.978699
0     1.182590
1     1.061766
2     1.178371
3     0.836467
4     0.862348
5     1.014719
6     0.945615
7     0.889275
8     1.086027
9     1.169211
10    1.204066
11    1.008233
0     0.991241
1     1.143298
2     1.086381
3     1.043513
4     0.853448
5     0.970266
        ...
6     0.646071
7     0.580913
8     0.634101
9     0.730665
10    0.697074
11    0.695029
0     0.693145
1     0.582942
2     0.781716
3     0.627840
4     0.628041
5     0.595944
6     0.603521
7     0.673715
8     0.709576
9     0.643659
10    0.697220
11    0.698129
0     0.607211
1     0.598727
2     0.584830
3     0.629344
4     0.598050
5     0.690355
6     0.767258
7     0.654089
8     0.666234
9     0.730070
10    0.632060
11    0.686320
Length: 108, dtype: float64

================================================================

<h3> CADMIO</h3>

================================================================

In [150]:
cadmio = pd.DataFrame()
totales_cd = []


    

for x in range(2008,2017):
    
    df = pd.read_excel('datos/CADMIO/Cd_DD_'+str(x)+'.xlsx', sep=";")
    df_ordenado_por_meses= df.sort_values(by=['MES'])
    # Nos interesa únicamente las mediciones diarias por meses de todas las estaciones, para poder sacar 
    # el valor mensual del contaminante:
    df_datos_diarios_por_mes = df_ordenado_por_meses.iloc[:,6:]
   
    
    totales_cd = []

    for p in range(1,13):
        
        medias_por_dia_mes = df_datos_diarios_por_mes[df_datos_diarios_por_mes['MES']== p ].iloc[:,1:].mean()
        media_por_mes = medias_por_dia_mes.mean()   
        totales_cd.append(media_por_mes)
    serie1 = pd.Series(totales_cd)
    
    cadmio['y'+str(x)] = serie1

In [151]:
cadmio

,y2008,y2009,y2010,y2011,y2012,y2013,y2014,y2015,y2016
0,0.768682,0.268450,0.319971,0.597228,0.409092,0.237212,0.330672,0.457093,0.265621
1,0.751601,0.334565,0.872867,0.527954,0.310422,0.226008,0.422378,0.419635,0.233798
2,0.556587,0.347869,0.509211,0.625509,0.383112,0.228387,0.377042,0.374004,0.269063
3,0.658350,0.256610,0.655548,0.432694,0.251013,0.226548,0.338825,0.236927,0.304686
4,0.852267,0.209933,0.541561,0.408431,0.373444,0.274561,0.266486,0.262585,0.276052
5,0.551104,0.185769,0.330963,0.362682,0.306669,0.223038,0.282623,0.295524,0.337532
6,0.285702,0.229854,0.368265,0.532380,0.243651,0.227609,0.284977,0.228025,0.303118
7,0.259706,0.186712,0.227088,0.228693,0.228688,0.218340,0.229572,0.284799,0.224062
8,0.327472,0.333221,0.313863,0.502783,0.237372,0.227401,0.259423,0.389007,0.266013
9,0.265128,0.344133,0.374217,0.625074,0.257380,0.231610,0.322873,0.372941,0.285453
10,0.271748,0.391711,0.556251,0.448438,0.258761,0.231021,0.261920,0.558232,0.514498
11,0.288800,0.323016,0.596198,0.359855,0.312898,0.252306,0.277126,0.503149,0.343502

In [152]:
serieCadmio= pd.Series()

for j in range(2008,2017):
        
    serieCadmio = serieCadmio.append(pd.Series(cadmio['y'+str(j)]))

serieCadmio

0     0.768682
1     0.751601
2     0.556587
3     0.658350
4     0.852267
5     0.551104
6     0.285702
7     0.259706
8     0.327472
9     0.265128
10    0.271748
11    0.288800
0     0.268450
1     0.334565
2     0.347869
3     0.256610
4     0.209933
5     0.185769
6     0.229854
7     0.186712
8     0.333221
9     0.344133
10    0.391711
11    0.323016
0     0.319971
1     0.872867
2     0.509211
3     0.655548
4     0.541561
5     0.330963
        ...
6     0.284977
7     0.229572
8     0.259423
9     0.322873
10    0.261920
11    0.277126
0     0.457093
1     0.419635
2     0.374004
3     0.236927
4     0.262585
5     0.295524
6     0.228025
7     0.284799
8     0.389007
9     0.372941
10    0.558232
11    0.503149
0     0.265621
1     0.233798
2     0.269063
3     0.304686
4     0.276052
5     0.337532
6     0.303118
7     0.224062
8     0.266013
9     0.285453
10    0.514498
11    0.343502
Length: 108, dtype: float64

================================================================

<h3> NIQUEL</h3>

================================================================

In [153]:
niquel = pd.DataFrame()
totales_ni = []


for x in range(2008,2017):
    
    df = pd.read_excel('datos/NIQUEL/Ni_DD_'+str(x)+'.xlsx', sep=";")
    df_ordenado_por_meses= df.sort_values(by=['MES'])
    # Nos interesa únicamente las mediciones diarias por meses de todas las estaciones, para poder sacar 
    # el valor mensual del contaminante:
    df_datos_diarios_por_mes = df_ordenado_por_meses.iloc[:,6:]
   
    
    totales_ni = []

    for p in range(1,13):
        
        medias_por_dia_mes = df_datos_diarios_por_mes[df_datos_diarios_por_mes['MES']== p ].iloc[:,1:].mean()
        media_por_mes = medias_por_dia_mes.mean()   
        totales_ni.append(media_por_mes)
    serie1 = pd.Series(totales_ni)
    
    niquel['y'+str(x)] = serie1

In [154]:
niquel

,y2008,y2009,y2010,y2011,y2012,y2013,y2014,y2015,y2016
0,6.056367,2.377731,2.724368,3.681202,3.487710,3.603344,3.385287,3.038793,2.474014
1,5.974355,3.454586,3.580769,3.729909,3.178939,5.190982,2.863393,2.904764,2.990014
2,4.933656,3.725914,3.236846,2.759707,3.963384,4.084679,3.610387,3.062229,2.347041
3,4.354272,3.108275,3.771553,4.025009,3.449913,5.278454,3.589760,3.498361,2.908468
4,5.091518,3.936860,3.496067,3.540596,4.113905,5.233464,3.454254,3.711972,3.134744
5,4.529125,4.102456,3.694290,3.268452,5.120588,5.407029,4.068952,3.365951,3.909265
6,5.016776,4.666987,3.810977,3.147215,4.017476,7.818538,4.062058,3.487548,4.053470
7,4.255050,3.971693,3.370527,4.077359,4.716114,5.401206,3.584353,3.193899,3.267760
8,4.204725,3.797754,3.379824,4.553489,4.203081,5.971830,3.904587,3.004559,3.219081
9,4.537419,4.297102,3.903407,3.617686,4.126908,4.345911,3.917946,3.086315,3.452619
10,3.308789,4.062513,3.931103,3.483386,3.616679,4.045017,2.802510,3.407053,2.181140
11,3.022981,2.987085,3.250050,3.149455,3.246529,7.335730,2.387740,3.535403,2.468221

In [155]:
serieNiquel= pd.Series()

for j in range(2008,2017):
        
    serieNiquel = serieNiquel.append(pd.Series(niquel['y'+str(j)]))

serieNiquel

0     6.056367
1     5.974355
2     4.933656
3     4.354272
4     5.091518
5     4.529125
6     5.016776
7     4.255050
8     4.204725
9     4.537419
10    3.308789
11    3.022981
0     2.377731
1     3.454586
2     3.725914
3     3.108275
4     3.936860
5     4.102456
6     4.666987
7     3.971693
8     3.797754
9     4.297102
10    4.062513
11    2.987085
0     2.724368
1     3.580769
2     3.236846
3     3.771553
4     3.496067
5     3.694290
        ...
6     4.062058
7     3.584353
8     3.904587
9     3.917946
10    2.802510
11    2.387740
0     3.038793
1     2.904764
2     3.062229
3     3.498361
4     3.711972
5     3.365951
6     3.487548
7     3.193899
8     3.004559
9     3.086315
10    3.407053
11    3.535403
0     2.474014
1     2.990014
2     2.347041
3     2.908468
4     3.134744
5     3.909265
6     4.053470
7     3.267760
8     3.219081
9     3.452619
10    2.181140
11    2.468221
Length: 108, dtype: float64

==============  CREACIÓN DATASET CONTAMINANTES ========================

In [192]:
df_contaminantes = pd.DataFrame({'cadmio': serieCadmio, 'niquel': serieNiquel, 'benpirenos': serieBenzopirenos, 'arsenico': serieArsenico})

In [193]:
df_contaminantes

    arsenico  benpirenos    cadmio    niquel
0   1.445264    0.281087  0.768682  6.056367
1   1.270137    0.215056  0.751601  5.974355
2   1.093210    0.120814  0.556587  4.933656
3   1.265506    0.073814  0.658350  4.354272
4   1.218206    0.063008  0.852267  5.091518
5   1.302040    0.074592  0.551104  4.529125
6   1.132523    0.073219  0.285702  5.016776
7   1.175340    0.058027  0.259706  4.255050
8   0.987349    0.067435  0.327472  4.204725
9   1.089588    0.137085  0.265128  4.537419
10  0.897953    0.241857  0.271748  3.308789
11  0.978699    0.390187  0.288800  3.022981
0   1.182590    0.166132  0.268450  2.377731
1   1.061766    0.167199  0.334565  3.454586
2   1.178371    0.116840  0.347869  3.725914
3   0.836467    0.096300  0.256610  3.108275
4   0.862348    0.057523  0.209933  3.936860
5   1.014719    0.057456  0.185769  4.102456
6   0.945615    0.056686  0.229854  4.666987
7   0.889275    0.055666  0.186712  3.971693
8   1.086027    0.063088  0.333221  3.797754
9   1.169211    0.113399  0.344133  4.297102
10  1.204066    0.182280  0.391711  4.062513
11  1.008233    0.147116  0.323016  2.987085
0   0.991241    0.298696  0.319971  2.724368
1   1.143298    0.256407  0.872867  3.580769
2   1.086381    0.157722  0.509211  3.236846
3   1.043513    0.100617  0.655548  3.771553
4   0.853448    0.071513  0.541561  3.496067
5   0.970266    0.067540  0.330963  3.694290
..       ...         ...       ...       ...
6   0.646071    0.066948  0.284977  4.062058
7   0.580913    0.064383  0.229572  3.584353
8   0.634101    0.115650  0.259423  3.904587
9   0.730665    0.121434  0.322873  3.917946
10  0.697074    0.226795  0.261920  2.802510
11  0.695029    0.462924  0.277126  2.387740
0   0.693145    0.429181  0.457093  3.038793
1   0.582942    0.228880  0.419635  2.904764
2   0.781716    0.122655  0.374004  3.062229
3   0.627840    0.071921  0.236927  3.498361
4   0.628041    0.061299  0.262585  3.711972
5   0.595944    0.063721  0.295524  3.365951
6   0.603521    0.080654  0.228025  3.487548
7   0.673715    0.075889  0.284799  3.193899
8   0.709576    0.067901  0.389007  3.004559
9   0.643659    0.099616  0.372941  3.086315
10  0.697220    0.288069  0.558232  3.407053
11  0.698129    0.584241  0.503149  3.535403
0   0.607211    0.304314  0.265621  2.474014
1   0.598727    0.216307  0.233798  2.990014
2   0.584830    0.131191  0.269063  2.347041
3   0.629344    0.132232  0.304686  2.908468
4   0.598050    0.141213  0.276052  3.134744
5   0.690355    0.101415  0.337532  3.909265
6   0.767258    0.135129  0.303118  4.053470
7   0.654089    0.093774  0.224062  3.267760
8   0.666234    0.141517  0.266013  3.219081
9   0.730070    0.179656  0.285453  3.452619
10  0.632060    0.363034  0.514498  2.181140
11  0.686320    0.581631  0.343502  2.468221

[108 rows x 4 columns]

In [194]:
fecha = pd.date_range('20080101', periods=108, freq='M')

In [195]:
fecha

DatetimeIndex(['2008-01-31', '2008-02-29', '2008-03-31', '2008-04-30',
               '2008-05-31', '2008-06-30', '2008-07-31', '2008-08-31',
               '2008-09-30', '2008-10-31',
               ...
               '2016-03-31', '2016-04-30', '2016-05-31', '2016-06-30',
               '2016-07-31', '2016-08-31', '2016-09-30', '2016-10-31',
               '2016-11-30', '2016-12-31'],
              dtype='datetime64[ns]', length=108, freq='M')

In [196]:
df_contaminantes['fecha'] = fecha

In [197]:
df_contaminantes

    arsenico  benpirenos    cadmio    niquel      fecha
0   1.445264    0.281087  0.768682  6.056367 2008-01-31
1   1.270137    0.215056  0.751601  5.974355 2008-02-29
2   1.093210    0.120814  0.556587  4.933656 2008-03-31
3   1.265506    0.073814  0.658350  4.354272 2008-04-30
4   1.218206    0.063008  0.852267  5.091518 2008-05-31
5   1.302040    0.074592  0.551104  4.529125 2008-06-30
6   1.132523    0.073219  0.285702  5.016776 2008-07-31
7   1.175340    0.058027  0.259706  4.255050 2008-08-31
8   0.987349    0.067435  0.327472  4.204725 2008-09-30
9   1.089588    0.137085  0.265128  4.537419 2008-10-31
10  0.897953    0.241857  0.271748  3.308789 2008-11-30
11  0.978699    0.390187  0.288800  3.022981 2008-12-31
0   1.182590    0.166132  0.268450  2.377731 2009-01-31
1   1.061766    0.167199  0.334565  3.454586 2009-02-28
2   1.178371    0.116840  0.347869  3.725914 2009-03-31
3   0.836467    0.096300  0.256610  3.108275 2009-04-30
4   0.862348    0.057523  0.209933  3.936860 2009-05-31
5   1.014719    0.057456  0.185769  4.102456 2009-06-30
6   0.945615    0.056686  0.229854  4.666987 2009-07-31
7   0.889275    0.055666  0.186712  3.971693 2009-08-31
8   1.086027    0.063088  0.333221  3.797754 2009-09-30
9   1.169211    0.113399  0.344133  4.297102 2009-10-31
10  1.204066    0.182280  0.391711  4.062513 2009-11-30
11  1.008233    0.147116  0.323016  2.987085 2009-12-31
0   0.991241    0.298696  0.319971  2.724368 2010-01-31
1   1.143298    0.256407  0.872867  3.580769 2010-02-28
2   1.086381    0.157722  0.509211  3.236846 2010-03-31
3   1.043513    0.100617  0.655548  3.771553 2010-04-30
4   0.853448    0.071513  0.541561  3.496067 2010-05-31
5   0.970266    0.067540  0.330963  3.694290 2010-06-30
..       ...         ...       ...       ...        ...
6   0.646071    0.066948  0.284977  4.062058 2014-07-31
7   0.580913    0.064383  0.229572  3.584353 2014-08-31
8   0.634101    0.115650  0.259423  3.904587 2014-09-30
9   0.730665    0.121434  0.322873  3.917946 2014-10-31
10  0.697074    0.226795  0.261920  2.802510 2014-11-30
11  0.695029    0.462924  0.277126  2.387740 2014-12-31
0   0.693145    0.429181  0.457093  3.038793 2015-01-31
1   0.582942    0.228880  0.419635  2.904764 2015-02-28
2   0.781716    0.122655  0.374004  3.062229 2015-03-31
3   0.627840    0.071921  0.236927  3.498361 2015-04-30
4   0.628041    0.061299  0.262585  3.711972 2015-05-31
5   0.595944    0.063721  0.295524  3.365951 2015-06-30
6   0.603521    0.080654  0.228025  3.487548 2015-07-31
7   0.673715    0.075889  0.284799  3.193899 2015-08-31
8   0.709576    0.067901  0.389007  3.004559 2015-09-30
9   0.643659    0.099616  0.372941  3.086315 2015-10-31
10  0.697220    0.288069  0.558232  3.407053 2015-11-30
11  0.698129    0.584241  0.503149  3.535403 2015-12-31
0   0.607211    0.304314  0.265621  2.474014 2016-01-31
1   0.598727    0.216307  0.233798  2.990014 2016-02-29
2   0.584830    0.131191  0.269063  2.347041 2016-03-31
3   0.629344    0.132232  0.304686  2.908468 2016-04-30
4   0.598050    0.141213  0.276052  3.134744 2016-05-31
5   0.690355    0.101415  0.337532  3.909265 2016-06-30
6   0.767258    0.135129  0.303118  4.053470 2016-07-31
7   0.654089    0.093774  0.224062  3.267760 2016-08-31
8   0.666234    0.141517  0.266013  3.219081 2016-09-30
9   0.730070    0.179656  0.285453  3.452619 2016-10-31
10  0.632060    0.363034  0.514498  2.181140 2016-11-30
11  0.686320    0.581631  0.343502  2.468221 2016-12-31

[108 rows x 5 columns]

In [198]:
df_contaminantes.dtypes

arsenico             float64
benpirenos           float64
cadmio               float64
niquel               float64
fecha         datetime64[ns]
dtype: object

In [199]:
df_contaminantes = df_contaminantes.set_index('fecha')

In [200]:
df_contaminantes

            arsenico  benpirenos    cadmio    niquel
fecha
2008-01-31  1.445264    0.281087  0.768682  6.056367
2008-02-29  1.270137    0.215056  0.751601  5.974355
2008-03-31  1.093210    0.120814  0.556587  4.933656
2008-04-30  1.265506    0.073814  0.658350  4.354272
2008-05-31  1.218206    0.063008  0.852267  5.091518
2008-06-30  1.302040    0.074592  0.551104  4.529125
2008-07-31  1.132523    0.073219  0.285702  5.016776
2008-08-31  1.175340    0.058027  0.259706  4.255050
2008-09-30  0.987349    0.067435  0.327472  4.204725
2008-10-31  1.089588    0.137085  0.265128  4.537419
2008-11-30  0.897953    0.241857  0.271748  3.308789
2008-12-31  0.978699    0.390187  0.288800  3.022981
2009-01-31  1.182590    0.166132  0.268450  2.377731
2009-02-28  1.061766    0.167199  0.334565  3.454586
2009-03-31  1.178371    0.116840  0.347869  3.725914
2009-04-30  0.836467    0.096300  0.256610  3.108275
2009-05-31  0.862348    0.057523  0.209933  3.936860
2009-06-30  1.014719    0.057456  0.185769  4.102456
2009-07-31  0.945615    0.056686  0.229854  4.666987
2009-08-31  0.889275    0.055666  0.186712  3.971693
2009-09-30  1.086027    0.063088  0.333221  3.797754
2009-10-31  1.169211    0.113399  0.344133  4.297102
2009-11-30  1.204066    0.182280  0.391711  4.062513
2009-12-31  1.008233    0.147116  0.323016  2.987085
2010-01-31  0.991241    0.298696  0.319971  2.724368
2010-02-28  1.143298    0.256407  0.872867  3.580769
2010-03-31  1.086381    0.157722  0.509211  3.236846
2010-04-30  1.043513    0.100617  0.655548  3.771553
2010-05-31  0.853448    0.071513  0.541561  3.496067
2010-06-30  0.970266    0.067540  0.330963  3.694290
...              ...         ...       ...       ...
2014-07-31  0.646071    0.066948  0.284977  4.062058
2014-08-31  0.580913    0.064383  0.229572  3.584353
2014-09-30  0.634101    0.115650  0.259423  3.904587
2014-10-31  0.730665    0.121434  0.322873  3.917946
2014-11-30  0.697074    0.226795  0.261920  2.802510
2014-12-31  0.695029    0.462924  0.277126  2.387740
2015-01-31  0.693145    0.429181  0.457093  3.038793
2015-02-28  0.582942    0.228880  0.419635  2.904764
2015-03-31  0.781716    0.122655  0.374004  3.062229
2015-04-30  0.627840    0.071921  0.236927  3.498361
2015-05-31  0.628041    0.061299  0.262585  3.711972
2015-06-30  0.595944    0.063721  0.295524  3.365951
2015-07-31  0.603521    0.080654  0.228025  3.487548
2015-08-31  0.673715    0.075889  0.284799  3.193899
2015-09-30  0.709576    0.067901  0.389007  3.004559
2015-10-31  0.643659    0.099616  0.372941  3.086315
2015-11-30  0.697220    0.288069  0.558232  3.407053
2015-12-31  0.698129    0.584241  0.503149  3.535403
2016-01-31  0.607211    0.304314  0.265621  2.474014
2016-02-29  0.598727    0.216307  0.233798  2.990014
2016-03-31  0.584830    0.131191  0.269063  2.347041
2016-04-30  0.629344    0.132232  0.304686  2.908468
2016-05-31  0.598050    0.141213  0.276052  3.134744
2016-06-30  0.690355    0.101415  0.337532  3.909265
2016-07-31  0.767258    0.135129  0.303118  4.053470
2016-08-31  0.654089    0.093774  0.224062  3.267760
2016-09-30  0.666234    0.141517  0.266013  3.219081
2016-10-31  0.730070    0.179656  0.285453  3.452619
2016-11-30  0.632060    0.363034  0.514498  2.181140
2016-12-31  0.686320    0.581631  0.343502  2.468221

[108 rows x 4 columns]

In [205]:
df_contaminantes.to_csv('contaminates_por_mes.csv')