In [8]:
import pandas as pd
import numpy as np

In [16]:
type(aux)

pandas.core.frame.DataFrame

In [17]:
lista_dias_del_meses = [31,28,31,30,31,30,31,31,30,31,30,31]

In [218]:
auxiliar = pd.DataFrame()
totales = []
conca 

    

for x in range(2001,2017):
    
    df = pd.read_excel('datos/PM_10/PM10_DD_'+str(x)+'.xlsx', sep=";")
    df_ordenado_por_meses= df.sort_values(by=['MES'])
    # Nos interesa Ãºnicamente las mediciones diarias por meses de todas las estaciones, para poder sacar 
    # el valor mensual del contaminante:
    df_datos_diarios_por_mes = df_ordenado_por_meses.iloc[:,6:]
   
    
    totales = []

    for p in range(1,13):
        
        medias_por_dia_mes = df_datos_diarios_por_mes[df_datos_diarios_por_mes['MES']== p ].iloc[:,1:].mean()
        media_por_mes = medias_por_dia_mes.mean()   
        totales.append(media_por_mes)
    serie1 = pd.Series(totales)
    
    auxiliar['y'+str(x)] = serie1

In [219]:
auxiliar

,y2001,y2002,y2003,y2004,y2005,y2006,y2007,y2008,y2009,y2010,y2011,y2012,y2013,y2014,y2015,y2016
0,47.293600,36.878094,24.812479,22.208213,27.465788,26.103168,36.270203,32.937238,18.927775,17.405147,25.596995,23.290370,18.221588,17.171058,20.498432,20.215709
1,55.128328,37.373950,25.993710,35.577635,29.242306,36.802329,29.698028,34.648043,25.483145,17.633227,26.295154,25.647738,17.103671,15.746431,18.960200,22.846952
2,32.606092,35.112357,38.067317,34.543537,40.497777,30.786894,29.645428,23.341674,28.733972,27.876883,21.305298,27.947710,16.154088,23.448508,21.428050,16.490487
3,28.833526,34.246774,29.736321,21.621801,32.012189,31.027896,30.702033,24.673716,19.232946,21.625204,24.652417,15.694662,18.254282,17.973531,20.854529,14.965678
4,31.295070,29.014845,30.096026,26.338370,34.735496,36.667626,30.537968,23.252266,28.558337,18.860221,20.999829,20.008141,16.831030,16.643651,21.844693,16.677103
5,32.786156,35.952304,39.753812,31.735655,38.475431,42.832881,27.853268,23.137711,25.661903,19.830960,19.593463,25.043164,20.632805,20.222209,20.558683,19.827451
6,30.895709,34.648614,33.494597,35.769257,35.124545,36.123316,31.530919,25.680810,25.631606,24.248480,21.316974,22.512195,23.621117,18.617661,25.231784,22.514125
7,31.055727,27.835951,33.645129,26.395983,29.128529,25.221841,29.695401,23.163241,23.567161,21.536846,23.102519,25.770377,21.252798,18.686920,20.670335,21.615365
8,29.503108,29.498977,27.977213,33.642223,29.504051,28.287671,29.153729,24.710823,22.742673,20.094987,21.991548,21.197685,20.630053,20.689025,17.744804,19.828938
9,31.723759,29.704568,21.944123,28.332649,26.643167,32.302350,26.472275,31.154252,23.445264,21.018377,24.441703,19.592631,20.032676,24.765134,19.242708,22.152234
10,28.172920,27.085234,28.220019,32.961873,22.349679,31.329759,38.893394,20.182580,27.309348,17.926363,19.247261,17.639701,16.972349,23.278579,22.327421,18.917833
11,30.501191,26.863580,22.810386,20.650977,25.690856,25.795844,28.287442,20.829772,17.708222,20.538174,17.943079,18.384498,23.007033,17.879183,34.644828,18.779441

In [176]:
type(auxiliar)

pandas.core.frame.DataFrame

In [177]:
len(auxiliar)

192

In [159]:
z = pd.Series(auxiliar[15][:12])

In [160]:
print(z)

0     47.293600
1     55.128328
2     32.606092
3     28.833526
4     31.295070
5     32.786156
6     30.895709
7     31.055727
8     29.503108
9     31.723759
10    28.172920
11    30.501191
dtype: float64

In [161]:
type(z)

pandas.core.series.Series

In [139]:
totales

[47.293600121500546,
 55.12832770668076,
 32.60609223349655,
 28.833526303889805,
 31.295070023254656,
 32.78615552600111,
 30.895708835414467,
 31.05572652451532,
 29.5031078633107,
 31.72375908131748,
 28.172920269021255,
 30.501190599587055,
 36.87809430065286,
 37.37394961275929,
 35.112357404071766,
 34.24677357841655,
 29.014845268029248,
 35.95230365161711,
 34.64861366828675,
 27.83595114941094,
 29.49897711063711,
 29.704568338179257,
 27.085233779031018,
 26.8635800729058,
 24.81247891166344,
 25.99371015232481,
 38.06731654486963,
 29.736321086802885,
 30.096026362604444,
 39.75381232794139,
 33.494597324985676,
 33.64512877545212,
 27.97721292271609,
 21.944122536620128,
 28.220019181335026,
 22.810386468239535,
 22.208213203086338,
 35.577634641877545,
 34.54353678088557,
 21.621800740930198,
 26.338370317661283,
 31.735654830452187,
 35.769257164738086,
 26.395983343215914,
 33.64222252896185,
 28.332649319005878,
 32.96187297501726,
 20.65097749416286,
 27.465787687070797,
 29.242306171449172,
 40.497776942179385,
 32.012188997023756,
 34.735495931270606,
 38.47543142417815,
 35.12454487309086,
 29.12852881482087,
 29.504051401889463,
 26.643167068280192,
 22.34967864572683,
 25.690856007963408,
 26.10316777039781,
 36.80232874488813,
 30.78689354495429,
 31.027896454159748,
 36.667625707148765,
 42.83288118587763,
 36.12331585194304,
 25.221841025270688,
 28.287670892006222,
 32.30235023240344,
 31.329759135638803,
 25.79584437451806,
 36.2702029875857,
 29.698027930044756,
 29.64542811105231,
 30.70203263461367,
 30.537968020000477,
 27.853267738888086,
 31.53091876516176,
 29.695401275421162,
 29.15372887882995,
 26.472274599588342,
 38.89339390083687,
 28.287442445921126,
 32.93723835991283,
 34.64804306157925,
 23.3416737810706,
 24.673715864117604,
 23.252266142758195,
 23.137710832049304,
 25.6808097744776,
 23.16324069751816,
 24.710823415300776,
 31.15425152685339,
 20.182579808775714,
 20.82977163250511,
 18.92777486093446,
 25.483144896797125,
 28.733971742788327,
 19.2329455313734,
 28.55833669040043,
 25.66190334551666,
 25.63160565757171,
 23.5671612963412,
 22.742672926011025,
 23.445264374700866,
 27.309347641127932,
 17.708222497506732,
 17.405147320268572,
 17.633226819559646,
 27.876883488197002,
 21.625204429927077,
 18.860221163700228,
 19.83096042674179,
 24.24848033172968,
 21.536846010842936,
 20.0949872508926,
 21.018377160656524,
 17.926363323183093,
 20.538174426969682,
 25.59699474794517,
 26.295154016938966,
 21.30529826619143,
 24.652416774352197,
 20.99982888851412,
 19.59346320950626,
 21.31697400692089,
 23.10251926797001,
 21.99154770164321,
 24.441703201819422,
 19.24726054264626,
 17.94307902305061,
 23.29036971199495,
 25.647737973012703,
 27.947709739263814,
 15.694662289468884,
 20.008140609301513,
 25.043164487924393,
 22.512194745049264,
 25.770376547396783,
 21.19768495386999,
 19.5926310805232,
 17.639700886062574,
 18.384497715531882,
 18.221587825537643,
 17.103670534054437,
 16.15408760673956,
 18.25428192203429,
 16.831029974193964,
 20.632804520763965,
 23.62111745662891,
 21.252797597981527,
 20.63005328129079,
 20.03267632392315,
 16.972348894074898,
 23.007033288985603,
 17.171057802170697,
 15.746430556034792,
 23.44850831613401,
 17.97353063056069,
 16.64365119810618,
 20.22220864620067,
 18.61766113671174,
 18.686919957322154,
 20.689024612327906,
 24.76513399515725,
 23.278578850103774,
 17.87918283183815,
 20.49843229813863,
 18.960199596252533,
 21.42804972593136,
 20.854528784609535,
 21.844692600623954,
 20.5586831551656,
 25.231783510455394,
 20.670335222284827,
 17.744803537231853,
 19.242708094954196,
 22.327421332773167,
 34.64482753060011,
 20.215708876772776,
 22.846951590641684,
 16.49048683583613,
 14.96567775509253,
 16.677102657781976,
 19.827451319549787,
 22.51412476373303,
 21.615364748004506,
 19.828937531441838,
 22.152234393811096,
 18.91783288289984,
 18.779441458535263]

In [140]:
pd.DataFrame(totales)

             0
0    47.293600
1    55.128328
2    32.606092
3    28.833526
4    31.295070
5    32.786156
6    30.895709
7    31.055727
8    29.503108
9    31.723759
10   28.172920
11   30.501191
12   36.878094
13   37.373950
14   35.112357
15   34.246774
16   29.014845
17   35.952304
18   34.648614
19   27.835951
20   29.498977
21   29.704568
22   27.085234
23   26.863580
24   24.812479
25   25.993710
26   38.067317
27   29.736321
28   30.096026
29   39.753812
..         ...
162  18.617661
163  18.686920
164  20.689025
165  24.765134
166  23.278579
167  17.879183
168  20.498432
169  18.960200
170  21.428050
171  20.854529
172  21.844693
173  20.558683
174  25.231784
175  20.670335
176  17.744804
177  19.242708
178  22.327421
179  34.644828
180  20.215709
181  22.846952
182  16.490487
183  14.965678
184  16.677103
185  19.827451
186  22.514125
187  21.615365
188  19.828938
189  22.152234
190  18.917833
191  18.779441

[192 rows x 1 columns]

In [142]:
len(totales)

192

In [144]:
for z in range(0,len(totales)):

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191