In [1]:
import pandas as pd
import numpy as np

In [20]:
import matplotlib.pyplot as plt
import seaborn as sns

In [21]:
%matplotlib inline

In [2]:
lista_dias_del_meses = [31,28,31,30,31,30,31,31,30,31,30,31]

================================================================

<h3> PARTÍCULAS PM 10 </h3>

================================================================

In [4]:
auxiliar = pd.DataFrame()
totales = []


    

for x in range(2001,2017):
    
    df = pd.read_excel('datos/PM_10/PM10_DD_'+str(x)+'.xlsx', sep=";")
    df_ordenado_por_meses= df.sort_values(by=['MES'])
    # Nos interesa únicamente las mediciones diarias por meses de todas las estaciones, para poder sacar 
    # el valor mensual del contaminante:
    df_datos_diarios_por_mes = df_ordenado_por_meses.iloc[:,6:]
   
    
    totales = []

    for p in range(1,13):
        
        medias_por_dia_mes = df_datos_diarios_por_mes[df_datos_diarios_por_mes['MES']== p ].iloc[:,1:].mean()
        media_por_mes = medias_por_dia_mes.mean()   
        totales.append(media_por_mes)
    serie1 = pd.Series(totales)
    
    auxiliar['y'+str(x)] = serie1

In [5]:
auxiliar

,y2001,y2002,y2003,y2004,y2005,y2006,y2007,y2008,y2009,y2010,y2011,y2012,y2013,y2014,y2015,y2016
0,47.293600,36.878094,24.812479,22.208213,27.465788,26.103168,36.270203,32.937238,18.927775,17.405147,25.596995,23.290370,18.221588,17.171058,20.498432,20.215709
1,55.128328,37.373950,25.993710,35.577635,29.242306,36.802329,29.698028,34.648043,25.483145,17.633227,26.295154,25.647738,17.103671,15.746431,18.960200,22.846952
2,32.606092,35.112357,38.067317,34.543537,40.497777,30.786894,29.645428,23.341674,28.733972,27.876883,21.305298,27.947710,16.154088,23.448508,21.428050,16.490487
3,28.833526,34.246774,29.736321,21.621801,32.012189,31.027896,30.702033,24.673716,19.232946,21.625204,24.652417,15.694662,18.254282,17.973531,20.854529,14.965678
4,31.295070,29.014845,30.096026,26.338370,34.735496,36.667626,30.537968,23.252266,28.558337,18.860221,20.999829,20.008141,16.831030,16.643651,21.844693,16.677103
5,32.786156,35.952304,39.753812,31.735655,38.475431,42.832881,27.853268,23.137711,25.661903,19.830960,19.593463,25.043164,20.632805,20.222209,20.558683,19.827451
6,30.895709,34.648614,33.494597,35.769257,35.124545,36.123316,31.530919,25.680810,25.631606,24.248480,21.316974,22.512195,23.621117,18.617661,25.231784,22.514125
7,31.055727,27.835951,33.645129,26.395983,29.128529,25.221841,29.695401,23.163241,23.567161,21.536846,23.102519,25.770377,21.252798,18.686920,20.670335,21.615365
8,29.503108,29.498977,27.977213,33.642223,29.504051,28.287671,29.153729,24.710823,22.742673,20.094987,21.991548,21.197685,20.630053,20.689025,17.744804,19.828938
9,31.723759,29.704568,21.944123,28.332649,26.643167,32.302350,26.472275,31.154252,23.445264,21.018377,24.441703,19.592631,20.032676,24.765134,19.242708,22.152234
10,28.172920,27.085234,28.220019,32.961873,22.349679,31.329759,38.893394,20.182580,27.309348,17.926363,19.247261,17.639701,16.972349,23.278579,22.327421,18.917833
11,30.501191,26.863580,22.810386,20.650977,25.690856,25.795844,28.287442,20.829772,17.708222,20.538174,17.943079,18.384498,23.007033,17.879183,34.644828,18.779441

================================================================

<h3> BENZOPIRENOS </h3>

================================================================

In [8]:
benzopirenos = pd.DataFrame()
totales_benzo = []


    

for x in range(2010,2017):
    
    df = pd.read_excel('datos/BENZOPIRENOS/benzopireno'+str(x)+'.xlsx', sep=";")
    df_ordenado_por_meses= df.sort_values(by=['MES'])
    # Nos interesa únicamente las mediciones diarias por meses de todas las estaciones, para poder sacar 
    # el valor mensual del contaminante:
    df_datos_diarios_por_mes = df_ordenado_por_meses.iloc[:,6:]
   
    
    totales_benzo = []

    for p in range(1,13):
        
        medias_por_dia_mes = df_datos_diarios_por_mes[df_datos_diarios_por_mes['MES']== p ].iloc[:,1:].mean()
        media_por_mes = medias_por_dia_mes.mean()   
        totales_benzo.append(media_por_mes)
    serie1 = pd.Series(totales_benzo)
    
    benzopirenos['y'+str(x)] = serie1

In [9]:
benzopirenos

       y2010     y2011     y2012     y2013     y2014     y2015     y2016
0   0.298696  0.338045  0.376155  0.324625  0.328150  0.429181  0.304314
1   0.256407  0.233718  0.283157  0.320554  0.159172  0.228880  0.216307
2   0.157722  0.123698  0.145749  0.120355  0.118629  0.122655  0.131191
3   0.100617  0.067127  0.078653  0.081658  0.081245  0.071921  0.132232
4   0.071513  0.064411  0.077773  0.072298  0.073954  0.061299  0.141213
5   0.067540  0.059992  0.073277  0.079319  0.072679  0.063721  0.101415
6   0.056475  0.060126  0.068019  0.584813  0.066948  0.080654  0.135129
7   0.062365  0.051317  0.070605  0.067683  0.064383  0.075889  0.093774
8   0.077519  0.071374  0.072345  0.077402  0.115650  0.067901  0.141517
9   0.141535  0.111641  0.102420  0.217555  0.121434  0.099616  0.179656
10  0.243834  0.198960  0.215338  0.208794  0.226795  0.288069  0.363034
11  0.434916  0.326662  0.305681  0.475331  0.462924  0.584241  0.581631

================================================================

<h3> PARTÍCULAS 2.5 </h3>

================================================================

In [16]:
pm25 = pd.DataFrame()
totales_pm25 = []


    

for x in range(2009,2017):
    
    df = pd.read_excel('datos/PM_2_5/PM2_5_'+str(x)+'.xlsx', sep=";")
    df_ordenado_por_meses= df.sort_values(by=['MES'])
    # Nos interesa únicamente las mediciones diarias por meses de todas las estaciones, para poder sacar 
    # el valor mensual del contaminante:
    df_datos_diarios_por_mes = df_ordenado_por_meses.iloc[:,6:]
   
    
    totales_pm25 = []

    for p in range(1,13):
        
        medias_por_dia_mes = df_datos_diarios_por_mes[df_datos_diarios_por_mes['MES']== p ].iloc[:,1:].mean()
        media_por_mes = medias_por_dia_mes.mean()   
        totales_pm25.append(media_por_mes)
    serie1 = pd.Series(totales_pm25)
    
    pm25['y'+str(x)] = serie1

In [17]:
pm25

,y2009,y2010,y2011,y2012,y2013,y2014,y2015,y2016
0,10.019166,9.627312,16.533783,15.613849,11.834837,10.761071,14.528960,12.585015
1,13.413926,10.459479,17.364894,16.095753,10.991193,8.982626,11.421466,12.138998
2,14.339257,15.788309,12.876882,16.860209,9.124274,13.175032,12.616592,9.973211
3,10.276743,12.786244,14.661859,9.635056,10.107784,10.216726,11.378150,7.935261
4,12.550319,10.715953,12.446747,11.364337,9.117599,9.158577,12.356034,8.874574
5,12.473253,10.672609,11.561033,12.890066,11.209215,11.285622,12.358295,11.167802
6,11.695893,12.860917,11.451728,12.033668,14.054037,10.372030,13.868549,11.993658
7,11.854021,11.280487,12.670336,13.705043,11.435059,10.337978,11.412451,10.806331
8,12.077693,10.231391,12.225491,12.101934,11.295613,12.105204,9.646703,11.026962
9,11.333856,11.177488,13.386428,11.728813,10.406346,13.182116,10.654395,11.806980
10,12.717407,10.282415,11.439384,11.082548,9.765985,11.843911,13.312027,11.280043
11,9.490390,12.724314,12.414808,12.628615,14.438559,11.603126,20.774549,12.661403

================================================================

<h3> ARSÉNICO</h3>

================================================================

In [13]:
arsenico = pd.DataFrame()
totales_as = []


    

for x in range(2008,2017):
    
    df = pd.read_excel('datos/ARSENICO/As_DD_'+str(x)+'.xlsx', sep=";")
    df_ordenado_por_meses= df.sort_values(by=['MES'])
    # Nos interesa únicamente las mediciones diarias por meses de todas las estaciones, para poder sacar 
    # el valor mensual del contaminante:
    df_datos_diarios_por_mes = df_ordenado_por_meses.iloc[:,6:]
   
    
    totales_as = []

    for p in range(1,13):
        
        medias_por_dia_mes = df_datos_diarios_por_mes[df_datos_diarios_por_mes['MES']== p ].iloc[:,1:].mean()
        media_por_mes = medias_por_dia_mes.mean()   
        totales_as.append(media_por_mes)
    serie1 = pd.Series(totales_as)
    
    arsenico['y'+str(x)] = serie1

In [14]:
arsenico

,y2008,y2009,y2010,y2011,y2012,y2013,y2014,y2015,y2016
0,1.445264,1.182590,0.991241,0.972411,0.982089,1.004395,0.666146,0.693145,0.607211
1,1.270137,1.061766,1.143298,0.991985,0.991102,1.308010,0.635351,0.582942,0.598727
2,1.093210,1.178371,1.086381,0.893003,1.083395,1.711879,0.757959,0.781716,0.584830
3,1.265506,0.836467,1.043513,0.798104,0.859820,0.807379,0.696055,0.627840,0.629344
4,1.218206,0.862348,0.853448,0.823411,0.941410,1.049278,0.632861,0.628041,0.598050
5,1.302040,1.014719,0.970266,1.128078,1.272288,0.898569,0.675564,0.595944,0.690355
6,1.132523,0.945615,0.990888,1.078082,0.953695,0.762031,0.646071,0.603521,0.767258
7,1.175340,0.889275,0.676997,1.046414,1.110710,0.875625,0.580913,0.673715,0.654089
8,0.987349,1.086027,0.896020,1.207515,1.015148,2.304110,0.634101,0.709576,0.666234
9,1.089588,1.169211,1.015055,1.186505,1.015388,0.752148,0.730665,0.643659,0.730070
10,0.897953,1.204066,0.911411,1.227376,0.895233,1.042350,0.697074,0.697220,0.632060
11,0.978699,1.008233,1.100444,0.867254,0.789536,2.320049,0.695029,0.698129,0.686320

================================================================

<h3> CADMIO</h3>

================================================================

In [18]:
cadmio = pd.DataFrame()
totales_cd = []


    

for x in range(2008,2017):
    
    df = pd.read_excel('datos/CADMIO/Cd_DD_'+str(x)+'.xlsx', sep=";")
    df_ordenado_por_meses= df.sort_values(by=['MES'])
    # Nos interesa únicamente las mediciones diarias por meses de todas las estaciones, para poder sacar 
    # el valor mensual del contaminante:
    df_datos_diarios_por_mes = df_ordenado_por_meses.iloc[:,6:]
   
    
    totales_cd = []

    for p in range(1,13):
        
        medias_por_dia_mes = df_datos_diarios_por_mes[df_datos_diarios_por_mes['MES']== p ].iloc[:,1:].mean()
        media_por_mes = medias_por_dia_mes.mean()   
        totales_cd.append(media_por_mes)
    serie1 = pd.Series(totales_cd)
    
    cadmio['y'+str(x)] = serie1

In [19]:
cadmio

,y2008,y2009,y2010,y2011,y2012,y2013,y2014,y2015,y2016
0,0.768682,0.268450,0.319971,0.597228,0.409092,1.709200,0.330672,0.457093,0.265621
1,0.751601,0.334565,0.872867,0.527954,0.310422,2.253688,0.422378,0.419635,0.233798
2,0.556587,0.347869,0.509211,0.625509,0.383112,2.097804,0.377042,0.374004,0.269063
3,0.658350,0.256610,0.655548,0.432694,0.251013,2.078442,0.338825,0.236927,0.304686
4,0.852267,0.209933,0.541561,0.408431,0.373444,1.603172,0.266486,0.262585,0.276052
5,0.551104,0.185769,0.330963,0.362682,0.306669,0.810779,0.282623,0.295524,0.337532
6,0.285702,0.229854,0.368265,0.532380,0.243651,3.128657,0.284977,0.228025,0.303118
7,0.259706,0.186712,0.227088,0.228693,0.228688,3.395293,0.229572,0.284799,0.224062
8,0.327472,0.333221,0.313863,0.502783,0.237372,4.014448,0.259423,0.389007,0.266013
9,0.265128,0.344133,0.374217,0.625074,0.257380,3.762864,0.322873,0.372941,0.285453
10,0.271748,0.391711,0.556251,0.448438,0.258761,3.820170,0.261920,0.558232,0.514498
11,0.288800,0.323016,0.596198,0.359855,0.312898,3.440445,0.277126,0.503149,0.343502

In [29]:
# ESTUDIAR LOS OUTLIERS

In [22]:
df_cadmio = pd.read_excel('datos/CADMIO/Cd_DD_2013.xlsx', sep=";")

In [24]:
df_cadmio = df_cadmio.sort_values(by=['MES'])

In [25]:
df_cadmio

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANNO,MES,D01,D02,D03,...,D22,D23,D24,D25,D26,D27,D28,D29,D30,D31
0,12,135,4,28,12135004_28_M,2013,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
544,8,19,42,28,08019042_28_M,2013,1,NaN,0.40,0.4000,...,0.40,0.40,NaN,NaN,0.40,NaN,NaN,0.40,0.40,0.4000
74,46,220,9,28,46220009_28_M,2013,1,NaN,NaN,0.0500,...,NaN,0.05,NaN,NaN,NaN,0.1200,NaN,NaN,0.18,NaN
943,29,32,1,28,29032001_28_M,2013,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
848,41,91,16,28,41091016_28_M,2013,1,NaN,NaN,NaN,...,NaN,NaN,0.23,NaN,NaN,NaN,1.20,NaN,NaN,NaN
1033,39,87,4,28,39087004_28_M,2013,1,NaN,NaN,NaN,...,NaN,NaN,NaN,0.4078,NaN,NaN,NaN,NaN,NaN,0.2922
825,4,32,5,28,04032005_28_M,2013,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,44.00,NaN,NaN,NaN
281,8,282,1,28,08282001_28_M,2013,1,NaN,NaN,NaN,...,0.10,NaN,NaN,NaN,NaN,NaN,0.10,NaN,NaN,NaN
980,48,20,6,28,48020006_28_M,2013,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
451,8,211,3,28,08211003_28_M,2013,1,NaN,NaN,NaN,...,NaN,NaN,NaN,1.6000,NaN,NaN,NaN,NaN,NaN,0.7000
709,10,182,1,28,10182001_28_M,2013,1,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0500,NaN,NaN,NaN,NaN,0.06,NaN
367,25,120,1,28,25120001_28_M,2013,1,NaN,NaN,0.2000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.20,NaN,NaN
1044,39,16,3,28,39016003_28_M,2013,1,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0903,NaN,NaN,NaN,NaN,NaN,0.7238
1161,11,33,10,28,11033010_28_M,2013,1,NaN,NaN,NaN,...,0.25,NaN,NaN,NaN,NaN,NaN,88.00,NaN,NaN,0.2200
191,12,32,5,28,12032005_28_M,2013,1,NaN,NaN,NaN,...,NaN,0.05,NaN,NaN,NaN,0.5800,NaN,NaN,1.61,NaN
60,12,99,1,28,12099001_28_M,2013,1,NaN,NaN,0.0500,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
151,3,105,1,28,03105001_28_M,2013,1,NaN,NaN,0.0500,...,NaN,0.05,NaN,NaN,NaN,0.0500,NaN,NaN,0.05,NaN
195,46,78,4,28,46078004_28_M,2013,1,NaN,NaN,0.1100,...,NaN,0.05,NaN,NaN,NaN,0.0500,NaN,NaN,0.05,NaN
790,21,5,2,28,21005002_28_M,2013,1,NaN,NaN,NaN,...,0.46,NaN,NaN,NaN,NaN,NaN,92.00,NaN,NaN,NaN
643,33,36,999,28,33036999_28_M,2013,1,0.02,NaN,NaN,...,NaN,NaN,NaN,0.0300,NaN,NaN,0.01,NaN,NaN,NaN
641,28,148,4,28,28148004_28_M,2013,1,NaN,0.29,0.2200,...,NaN,0.16,NaN,0.1200,NaN,NaN,0.12,NaN,0.12,0.1700
640,28,92,5,28,28092005_28_M,2013,1,NaN,0.12,0.2000,...,NaN,0.12,NaN,0.1200,NaN,NaN,0.12,NaN,0.12,0.1200
639,28,16,1,28,28016001_28_M,2013,1,NaN,0.19,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.12,NaN,NaN,NaN
872,11,31,1,28,11031001_28_M,2013,1,NaN,NaN,NaN,...,26.00,NaN,NaN,NaN,NaN,NaN,52.00,NaN,NaN,NaN
1001,1,59,9,28,01059009_28_M,2013,1,NaN,NaN,NaN,...,0.20,0.20,0.20,0.2000,0.20,0.2000,0.20,0.20,0.20,0.2000
593,8,19,54,28,08019054_28_M,2013,1,0.40,0.40,0.4000,...,0.40,0.40,0.40,NaN,0.40,0.4000,0.40,0.40,0.40,0.4000
802,21,50,1,28,21050001_28_M,2013,1,NaN,NaN,NaN,...,0.28,NaN,NaN,NaN,NaN,NaN,1.40,NaN,NaN,NaN
727,14,21,7,28,14021007_28_M,2013,1,NaN,NaN,NaN,...,1.40,NaN,NaN,NaN,NaN,NaN,1.10,NaN,NaN,NaN
578,8,19,45,28,08019045_28_M,2013,1,0.40,NaN,0.4000,...,0.40,0.40,0.40,0.4000,0.40,0.4000,0.40,0.40,0.40,0.4000
163,12,46,1,28,12046001_28_M,2013,1,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,0.05,0.0500,NaN,0.05,0.05,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1012,1,59,9,28,01059009_28_M,2013,12,0.20,0.20,0.2000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1021,39,20,1,28,39020001_28_M,2013,12,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1032,39,59,1,28,39059001_28_M,2013,12,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1043,39,87,4,28,39087004_28_M,2013,12,NaN,NaN,0.4171,...,NaN,NaN,NaN,NaN,NaN,0.0904,NaN,NaN,NaN,NaN
1055,39,16,3,28,39016003_28_M,2013,12,NaN,NaN,2.1225,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
824,14,21,8,28,14021008_28_M,2013,12,0.35,NaN,NaN,...,4.40,2.60,0.98,5.0000,1.40,1.7000,51.00,21.00,NaN,NaN
531,8,19,55,28,08019055_28_M,2013,12,NaN,NaN,0.4000,...,0.40,0.40,0.40,0.4000,0.40,0.4000,0.40,0.40,0.40,0.4000
813,21,50,1,28,21050001_28_M,2013,12,NaN,NaN,0.3600,...,NaN,NaN,NaN,NaN,0.24,NaN,NaN,NaN,NaN,NaN
789,14,21,7,28,14021007_28_M,2013,12,NaN,NaN,52.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
559,8,19,42,28,08019042_28_M,2013,12,0.40,0.40,0.4000,...,0.40,0.40,0.40,0.4000,0.40,0.4000,0.40,0.40,0.40,0.4000
577,8,19,28,28,08019028_28_M,2013,12,0.40,0.40,0.4000,...,0.40,0.40,0.40,0.4000,NaN,0.4000,0.40,0.40,0.40,0.4000
592,8,19,45,28,08019045_28_M,2013,12,0.40,0.40,0.4000,...,0.40,0.40,0.40,0.4000,0.40,0.4000,0.40,0.40,0.40,0.4000
604,8,19,54,28,08019054_28_M,2013,12,0.40,0.40,0.4000,...,0.40,0.40,0.40,0.4000,0.40,0.4000,0.40,0.40,0.40,0.4000
607,28,148,4,28,28148004_28_M,2013,12,NaN,0.12,0.1200,...,NaN,0.12,NaN,NaN,0.12,0.1200,NaN,NaN,0.12,0.1200
608,28,92,5,28,28092005_28_M,2013,12,NaN,0.12,NaN,...,NaN,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
609,28,16,1,28,28016001_28_M,2013,12,NaN,0.12,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
650,6,15,1,28,06015001_28_M,2013,12,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.03,NaN,NaN
673,6,158,1,28,06158001_28_M,2013,12,0.04,NaN,NaN,...,NaN,NaN,NaN,NaN,0.10,NaN,NaN,NaN,NaN,0.0500
680,10,37,1,28,10037001_28_M,2013,12,NaN,NaN,0.1800,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
686,10,148,1,28,10148001_28_M,2013,12,NaN,NaN,NaN,...,NaN,NaN,NaN,0.0100,NaN,NaN,NaN,NaN,0.04,NaN
698,10,182,1,28,10182001_28_M,2013,12,NaN,NaN,NaN,...,NaN,NaN,0.12,NaN,NaN,NaN,NaN,0.01,NaN,NaN
716,7,54,1,28,07054001_28_M,2013,12,0.07,0.07,0.0700,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
719,46,242,1,28,46242001_28_M,2013,12,NaN,NaN,0.0500,...,NaN,NaN,NaN,NaN,NaN,0.0000,0.00,NaN,0.00,0.0000
726,11,22,5,28,11022005_28_M,2013,12,NaN,NaN,71.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
728,18,87,7,28,18087007_28_M,2013,12,NaN,NaN,0.1500,...,NaN,NaN,0.63,NaN,NaN,63.0000,NaN,NaN,NaN,NaN
755,29,67,6,28,29067006_28_M,2013,12,0.07,NaN,0.2100,...,NaN,NaN,0.16,NaN,NaN,0.3200,NaN,NaN,NaN,NaN
766,23,10,2,28,23010002_28_M,2013,12,NaN,NaN,0.1400,...,NaN,NaN,NaN,NaN,NaN,0.1000,NaN,NaN,NaN,NaN
776,41,4,6,28,41004006_28_M,2013,12,NaN,NaN,0.1200,...,NaN,NaN,NaN,NaN,NaN,83.0000,NaN,NaN,NaN,NaN
801,21,5,2,28,21005002_28_M,2013,12,NaN,NaN,45.0000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1179,11,33,10,28,11033010_28_M,2013,12,55.00,NaN,53.0000,...,0.09,84.00,0.16,59.0000,57.00,57.0000,44.00,0.12,NaN,NaN

================================================================

<h3> NIQUEL</h3>

================================================================

In [32]:
niquel = pd.DataFrame()
totales_ni = []


    

for x in range(2008,2017):
    
    df = pd.read_excel('datos/NIQUEL/Ni_DD_'+str(x)+'.xlsx', sep=";")
    df_ordenado_por_meses= df.sort_values(by=['MES'])
    # Nos interesa únicamente las mediciones diarias por meses de todas las estaciones, para poder sacar 
    # el valor mensual del contaminante:
    df_datos_diarios_por_mes = df_ordenado_por_meses.iloc[:,6:]
   
    
    totales_ni = []

    for p in range(1,13):
        
        medias_por_dia_mes = df_datos_diarios_por_mes[df_datos_diarios_por_mes['MES']== p ].iloc[:,1:].mean()
        media_por_mes = medias_por_dia_mes.mean()   
        totales_ni.append(media_por_mes)
    serie1 = pd.Series(totales_ni)
    
    niquel['y'+str(x)] = serie1

In [33]:
niquel

,y2008,y2009,y2010,y2011,y2012,y2013,y2014,y2015,y2016
0,6.056367,2.377731,2.724368,3.681202,3.487710,3.603344,3.385287,3.038793,2.474014
1,5.974355,3.454586,3.580769,3.729909,3.178939,5.190982,2.863393,2.904764,2.990014
2,4.933656,3.725914,3.236846,2.759707,3.963384,4.084679,3.610387,3.062229,2.347041
3,4.354272,3.108275,3.771553,4.025009,3.449913,5.278454,3.589760,3.498361,2.908468
4,5.091518,3.936860,3.496067,3.540596,4.113905,5.233464,3.454254,3.711972,3.134744
5,4.529125,4.102456,3.694290,3.268452,5.120588,5.407029,4.068952,3.365951,3.909265
6,5.016776,4.666987,3.810977,3.147215,4.017476,7.818538,4.062058,3.487548,4.053470
7,4.255050,3.971693,3.370527,4.077359,4.716114,5.401206,3.584353,3.193899,3.267760
8,4.204725,3.797754,3.379824,4.553489,4.203081,5.971830,3.904587,3.004559,3.219081
9,4.537419,4.297102,3.903407,3.617686,4.126908,4.345911,3.917946,3.086315,3.452619
10,3.308789,4.062513,3.931103,3.483386,3.616679,4.045017,2.802510,3.407053,2.181140
11,3.022981,2.987085,3.250050,3.149455,3.246529,7.335730,2.387740,3.535403,2.468221