In [213]:
import pandas as pd
import numpy as np

In [214]:
import matplotlib.pyplot as plt
import seaborn as sns

In [215]:
%matplotlib inline

In [216]:
df = pd.read_csv('datos/2013/Diarios/As_2013_DD.csv', sep=";")

In [217]:
df.head()

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANNO,MES,D01,D02,D03,...,D22,D23,D24,D25,D26,D27,D28,D29,D30,D31
0,12,135,4,17,12135004_17_M,2013,4,NaN,NaN,NaN,...,0.35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,12,135,4,17,12135004_17_M,2013,6,0.35,NaN,1.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.67,NaN,NaN
2,12,135,4,17,12135004_17_M,2013,7,1.39,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.69,NaN,NaN
3,12,135,4,17,12135004_17_M,2013,8,2.21,1.66,NaN,...,NaN,NaN,0.97,NaN,2.50,NaN,NaN,3.64,2.65,NaN
4,12,135,4,17,12135004_17_M,2013,9,1.26,1.12,NaN,...,NaN,1.67,NaN,NaN,1.11,1.66,NaN,0.55,1.51,NaN

In [230]:
df.fillna(0, inplace=True)

In [231]:
df

,PROVINCIA,MUNICIPIO,ESTACION,MAGNITUD,PUNTO_MUESTREO,ANNO,MES,D01,D02,D03,...,D22,D23,D24,D25,D26,D27,D28,D29,D30,D31
0,12,135,4,17,12135004_17_M,2013,4,0.000,0.000,0.000,...,0.350,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000
1,12,135,4,17,12135004_17_M,2013,6,0.350,0.000,1.500,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,1.670,0.000,0.000
2,12,135,4,17,12135004_17_M,2013,7,1.390,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.690,0.000,0.000
3,12,135,4,17,12135004_17_M,2013,8,2.210,1.660,0.000,...,0.000,0.000,0.970,0.000,2.500,0.000,0.0000,3.640,2.650,0.000
4,12,135,4,17,12135004_17_M,2013,9,1.260,1.120,0.000,...,0.000,1.670,0.000,0.000,1.110,1.660,0.0000,0.550,1.510,0.000
5,12,135,4,17,12135004_17_M,2013,10,0.000,0.000,1.380,...,0.000,0.000,1.110,2.230,0.000,1.810,2.3600,0.000,0.700,0.000
6,12,135,4,17,12135004_17_M,2013,11,0.000,1.690,0.000,...,0.210,0.000,0.070,0.000,0.000,0.500,0.0000,0.000,2.830,0.000
7,12,135,4,17,12135004_17_M,2013,12,0.000,0.570,0.000,...,0.000,2.370,0.000,0.140,0.000,0.000,2.8800,0.000,0.700,0.000
8,12,124,1,17,12124001_17_M,2013,1,0.000,0.000,0.000,...,0.000,0.350,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000
9,12,124,1,17,12124001_17_M,2013,2,0.000,0.000,0.000,...,0.000,0.350,0.000,0.350,0.000,0.000,0.0000,0.000,0.000,0.000
10,12,124,1,17,12124001_17_M,2013,3,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000
11,12,124,1,17,12124001_17_M,2013,4,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000
12,12,124,1,17,12124001_17_M,2013,6,0.350,0.000,0.820,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.700,0.000,0.000
13,12,124,1,17,12124001_17_M,2013,7,0.560,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.550,0.0000,0.560,0.000,0.000
14,12,124,1,17,12124001_17_M,2013,8,2.770,1.800,0.000,...,0.000,0.000,0.560,0.000,0.000,0.000,0.0000,0.280,0.980,0.000
15,12,124,1,17,12124001_17_M,2013,9,1.960,1.260,0.000,...,0.000,0.700,0.000,0.000,0.000,0.000,0.0000,0.420,0.690,0.000
16,12,124,1,17,12124001_17_M,2013,10,0.000,0.000,0.140,...,0.000,0.000,0.840,0.420,0.000,0.980,0.5600,0.000,0.140,0.000
17,12,124,1,17,12124001_17_M,2013,11,0.000,0.710,0.000,...,0.000,0.000,0.070,0.000,0.000,0.070,0.0000,0.000,0.140,0.000
18,12,124,1,17,12124001_17_M,2013,12,0.000,0.280,0.000,...,0.000,0.850,0.000,0.140,0.000,0.000,0.0000,0.000,0.000,0.000
19,12,135,4,17,12135004_17_M,2013,1,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000
20,12,135,4,17,12135004_17_M,2013,2,0.000,0.000,0.000,...,0.000,0.350,0.000,0.350,0.000,0.000,0.0000,0.000,0.000,0.000
21,12,135,4,17,12135004_17_M,2013,3,0.000,0.000,0.000,...,0.000,1.240,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000
22,46,250,43,17,46250043_17_M,2013,7,0.140,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000
23,46,250,43,17,46250043_17_M,2013,8,0.270,0.140,0.000,...,0.140,0.000,0.270,0.000,0.000,0.000,0.0000,0.140,0.280,0.000
24,46,250,43,17,46250043_17_M,2013,9,0.690,0.550,0.000,...,0.000,0.280,0.000,0.000,0.410,0.410,0.0000,0.000,0.000,0.000
25,46,250,43,17,46250043_17_M,2013,10,0.000,0.000,0.270,...,0.000,0.000,0.280,0.410,0.000,0.410,0.5500,0.000,0.000,0.000
26,46,250,43,17,46250043_17_M,2013,11,0.000,0.280,0.000,...,0.070,0.000,0.070,0.000,0.000,0.210,0.0000,0.000,0.280,0.000
27,46,250,43,17,46250043_17_M,2013,12,0.000,0.420,0.000,...,0.000,0.420,0.000,0.140,0.000,0.000,0.1400,0.000,0.280,0.000
28,46,250,43,17,46250043_17_M,2013,1,0.000,0.000,0.350,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.350,0.000
29,46,250,43,17,46250043_17_M,2013,2,0.350,0.000,0.000,...,0.000,0.350,0.000,0.350,0.000,0.000,0.3500,0.000,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1149,2,3,1,17,02003001_17_M,2013,7,0.000,0.000,0.000,...,0.000,0.700,0.000,0.000,0.000,0.000,0.0000,0.000,0.700,0.000
1150,2,3,1,17,02003001_17_M,2013,8,0.000,0.000,0.000,...,0.000,0.700,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000
1151,13,71,15,17,13071015_17_M,2013,8,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000
1152,13,71,15,17,13071015_17_M,2013,9,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.700,0.000
1153,45,168,2,17,45168002_17_M,2013,6,0.000,0.000,0.000,...,0.000,0.000,0.700,0.000,0.000,0.000,0.0000,0.000,0.000,0.000
1154,45,168,2,17,45168002_17_M,2013,7,0.700,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000
1155,11,33,10,17,11033010_17_M,2013,1,0.000,0.000,0.000,...,0.510,0.000,0.000,0.000,0.000,0.000,0.3100,0.000,0.000,1.200
1156,11,33,10,17,11033010_17_M,2013,2,1.100,0.540,0.077,...,0.000,0.000,0.620,0.000,0.000,0.000,0.4100,0.000,0.000,0.000
1157,11,33,10,17,11033010_17_M,2013,3,0.890,0.220,0.250,...,0.000,0.000,0.000,0.840,0.620,0.170,0.2100,0.190,0.200,0.130
1158,11,33,10,17,11033010_17_M,2013,4,0.360,0.390,0.240,...,0.970,0.250,0.290,0.640,1.300,0.750,0.7400,0.840,0.580,0.000
1159,11,33,10,17,11033010_17_M,2013,5,0.230,2.100,2.100,...,0.000,0.005,0.005,0.005,0.005,0.005,0.0050,0.005,0.005,0.005
1160,11,33,10,17,11033010_17_M,2013,6,0.005,0.005,0.000,...,0.005,0.120,0.047,0.170,0.240,0.280,0.0099,0.230,0.230,0.000
1161,11,33,10,17,11033010_17_M,2013,7,0.000,0.000,0.000,...,0.000,0.000,6.000,0.000,0.000,0.000,0.0000,0.000,7.200,1.000
1162,11,33,10,17,11033010_17_M,2013,8,0.750,0.230,0.750,...,0.000,0.420,0.000,0.000,0.340,0.340,0.3100,0.220,0.170,0.190
1163,11,33,10,17,11033010_17_M,2013,9,0.390,0.370,0.230,...,0.160,0.230,0.230,0.380,0.420,0.550,0.1500,0.150,0.000,0.000
1164,11,33,10,17,11033010_17_M,2013,10,0.380,4.900,5.600,...,0.260,0.340,0.840,0.600,0.370,0.200,1.4000,0.490,0.500,0.170
1165,11,33,10,17,11033010_17_M,2013,11,0.180,0.170,0.790,...,0.530,0.440,0.360,0.680,1.000,0.710,0.4900,0.490,0.930,0.000
1166,11,33,10,17,11033010_17_M,2013,12,0.330,0.000,0.160,...,0.120,0.220,0.380,0.400,0.280,0.210,0.3200,0.230,0.000,0.000
1167,18,87,10,17,18087010_17_M,2013,1,0.000,0.000,0.000,...,0.200,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000
1168,18,87,10,17,18087010_17_M,2013,2,0.000,0.000,0.000,...,0.000,0.000,0.200,0.000,0.000,0.000,0.0000,0.000,0.000,0.000
1169,18,87,10,17,18087010_17_M,2013,3,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.200,0.000,0.0000,0.000,0.000,0.000
1170,18,87,10,17,18087010_17_M,2013,4,0.200,0.000,0.000,...,0.000,0.000,0.000,0.200,0.000,0.000,0.0000,0.000,0.000,0.000
1171,18,87,10,17,18087010_17_M,2013,5,0.200,0.000,0.000,...,0.000,0.000,0.000,0.200,0.000,0.000,0.0000,0.000,0.000,0.200
1172,18,87,10,17,18087010_17_M,2013,6,0.000,0.000,0.000,...,0.000,0.000,0.200,0.000,0.000,0.000,0.0000,0.000,0.200,0.000
1173,18,87,10,17,18087010_17_M,2013,7,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000
1174,18,87,10,17,18087010_17_M,2013,8,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.220,0.000,0.000
1175,18,87,10,17,18087010_17_M,2013,9,0.000,0.000,0.000,...,0.240,0.000,0.000,0.000,0.000,0.000,0.1800,0.000,0.000,0.000
1176,18,87,10,17,18087010_17_M,2013,10,0.000,0.000,0.000,...,0.240,0.000,0.000,0.000,0.000,0.000,0.3800,0.000,0.000,0.000
1177,18,87,10,17,18087010_17_M,2013,11,0.000,0.000,0.270,...,0.000,0.000,0.000,0.000,0.000,0.200,0.0000,0.000,0.000,0.000
1178,18,87,10,17,18087010_17_M,2013,12,0.000,0.000,0.230,...,0.000,0.000,0.000,0.000,0.000,0.000,0.0000,0.000,0.000,0.000

In [232]:
ordenado = df.sort_values(by=['MES'])

In [233]:
lista_meses = ordenado['MES'].unique()

In [234]:
lista_meses

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [235]:
suma =0
for x in lista_meses:
    suma += len(df[df['MES']==x])
    print(len(df[df['MES']==x]))

# comprobamos que coincide el nÃºmero de registros con la suma de las repeticiones de los meses
print("Total observaciones: ",suma)

98
99
99
98
82
104
102
101
100
100
100
96
Total observaciones:  1179

In [240]:
lista = (df[df['MES']==1]==0).sum(axis=1).tolist()

In [111]:
(df['MES']==1) == np.nan

0       False
1       False
2       False
3       False
4       False
5       False
6       False
7       False
8       False
9       False
10      False
11      False
12      False
13      False
14      False
15      False
16      False
17      False
18      False
19      False
20      False
21      False
22      False
23      False
24      False
25      False
26      False
27      False
28      False
29      False
        ...
1149    False
1150    False
1151    False
1152    False
1153    False
1154    False
1155    False
1156    False
1157    False
1158    False
1159    False
1160    False
1161    False
1162    False
1163    False
1164    False
1165    False
1166    False
1167    False
1168    False
1169    False
1170    False
1171    False
1172    False
1173    False
1174    False
1175    False
1176    False
1177    False
1178    False
Name: MES, Length: 1179, dtype: bool

In [241]:
len(lista)

98

In [242]:
for x in lista:
    print(x)

24
30
25
25
17
27
22
18
18
18
22
18
18
18
20
21
18
22
18
18
18
18
22
27
27
26
26
26
26
27
27
27
26
26
27
27
27
27
26
26
27
2
27
30
26
12
6
11
8
2
5
7
1
26
15
15
26
26
26
26
26
25
26
27
25
28
28
26
26
27
27
27
26
26
27
26
26
26
26
26
27
0
15
28
11
8
27
29
29
27
25
19
25
12
12
21
13
29

In [243]:
lista_dia_meses = [31,28,31,30,31,30,31,31,30,31,30,31]

In [201]:
lista_dia_meses[0]

31

In [244]:
# definir funciÃ³n para recorrer todos los dÃ­as por cada mes, obteniendo la media diviendo para ello entre el nÃºmero
# de dÃ­as que existen mediciones

In [245]:
df_numerico = df.iloc[:,6:]

In [246]:
df_numerico.head()

,MES,D01,D02,D03,D04,D05,D06,D07,D08,D09,...,D22,D23,D24,D25,D26,D27,D28,D29,D30,D31
0,4,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.0,0.00,...,0.35,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0
1,6,0.35,0.00,1.5,0.00,0.00,1.64,1.64,0.0,0.00,...,0.00,0.00,0.00,0.0,0.00,0.00,0.0,1.67,0.00,0.0
2,7,1.39,0.00,0.0,1.66,1.66,0.00,0.00,1.1,0.00,...,0.00,0.00,0.00,0.0,0.00,0.00,0.0,0.69,0.00,0.0
3,8,2.21,1.66,0.0,2.76,0.97,0.00,0.83,0.0,0.00,...,0.00,0.00,0.97,0.0,2.50,0.00,0.0,3.64,2.65,0.0
4,9,1.26,1.12,0.0,5.59,0.00,0.00,12.27,0.0,1.82,...,0.00,1.67,0.00,0.0,1.11,1.66,0.0,0.55,1.51,0.0

In [249]:
(df['D03']>0).sum()

340

In [250]:
(df['D03']==0).sum()

839

In [251]:
340 + 839

1179

In [252]:
mes1 = df[df['MES']==2].iloc[:,7:]

In [253]:
df[df['MES']==2].iloc[:,7:].sum()

D01    22.8800
D02    10.6600
D03    11.1370
D04    28.0000
D05    18.5700
D06    33.5431
D07    12.7600
D08    23.1600
D09    14.3400
D10    23.2900
D11    16.6300
D12    23.3605
D13    31.2000
D14    24.6000
D15    29.6100
D16    17.3500
D17    28.5000
D18    48.6701
D19    20.4600
D20    40.5500
D21    21.3600
D22    18.8700
D23    17.9200
D24    21.2415
D25    32.8100
D26    18.4600
D27    16.2400
D28    29.9500
D29     0.0000
D30     0.0000
D31     0.0000
dtype: float64

In [259]:
lista = (df[df['MES']==1]==0).sum(axis=1).tolist()

In [261]:
len(lista)

98

In [278]:
serie_meses = []

for x in range(1,13):
   
    mes_temporal = df[df['MES']== x]
    
    listado = (mes_temporal==0).sum(axis=1).tolist()
    sumatorio = 0
    
    for z in range(len(listado)):
        
        df_reducido = mes_temporal.iloc[:,7:]
        dias_nulos_mes = listado[z]
        #dias_nulos_mes = df_reducido.iloc[0].isnull().sum()
        if((lista_dia_meses[x-1]-dias_nulos_mes) == 0):
            sumatorio = sumatorio + df_reducido.iloc[0].sum()            
        else: 
            sumatorio = sumatorio + df_reducido.iloc[0].sum()/((lista_dia_meses[x-1])-dias_nulos_mes)
            
                
    serie_meses.append(sumatorio)
    
    
print(serie_meses)

[44.64320999053156]
[44.64320999053156, 154.67468692515217]
[44.64320999053156, 154.67468692515217, 33.06634240414252]
[44.64320999053156, 154.67468692515217, 33.06634240414252, 134.65422177693782]
[44.64320999053156, 154.67468692515217, 33.06634240414252, 134.65422177693782, 0.7413881545523633]
[44.64320999053156, 154.67468692515217, 33.06634240414252, 134.65422177693782, 0.7413881545523633, 210.40140136873518]
[44.64320999053156, 154.67468692515217, 33.06634240414252, 134.65422177693782, 0.7413881545523633, 210.40140136873518, 246.84994660396347]
[44.64320999053156, 154.67468692515217, 33.06634240414252, 134.65422177693782, 0.7413881545523633, 210.40140136873518, 246.84994660396347, 375.79696852264647]
[44.64320999053156, 154.67468692515217, 33.06634240414252, 134.65422177693782, 0.7413881545523633, 210.40140136873518, 246.84994660396347, 375.79696852264647, 600.8948146689513]
[44.64320999053156, 154.67468692515217, 33.06634240414252, 134.65422177693782, 0.7413881545523633, 210.40140136873518, 246.84994660396347, 375.79696852264647, 600.8948146689513, 228.07290243906684]
[44.64320999053156, 154.67468692515217, 33.06634240414252, 134.65422177693782, 0.7413881545523633, 210.40140136873518, 246.84994660396347, 375.79696852264647, 600.8948146689513, 228.07290243906684, 190.01973478150197]
[44.64320999053156, 154.67468692515217, 33.06634240414252, 134.65422177693782, 0.7413881545523633, 210.40140136873518, 246.84994660396347, 375.79696852264647, 600.8948146689513, 228.07290243906684, 190.01973478150197, 267.1525781959334]
[44.64320999053156, 154.67468692515217, 33.06634240414252, 134.65422177693782, 0.7413881545523633, 210.40140136873518, 246.84994660396347, 375.79696852264647, 600.8948146689513, 228.07290243906684, 190.01973478150197, 267.1525781959334]

In [265]:
calcular = df[df['MES']==1].iloc[:,7:]

In [266]:
type(calcular)

pandas.core.frame.DataFrame

In [268]:
(df[df['MES']==1]==0).sum(axis=1)

8       24
19      30
28      25
41      25
43      17
53      27
56      22
65      18
88      18
94      18
113     22
117     18
127     18
132     18
158     20
164     21
169     18
179     22
193     18
204     18
224     18
225     18
237     22
253     27
265     27
280     26
292     26
301     26
324     26
333     27
        ..
798     26
810     27
833     27
845     27
856     26
868     26
880     27
891     26
903     26
915     26
926     26
938     26
949     27
965      0
978     15
984     28
995     11
1007     8
1029    27
1041    29
1053    29
1063    27
1069    25
1108    19
1109    25
1115    12
1120    12
1137    21
1155    13
1167    29
Length: 98, dtype: int64

In [269]:
for z in range(len(lista)):
    print(z)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97

In [270]:
lista

[24,
 30,
 25,
 25,
 17,
 27,
 22,
 18,
 18,
 18,
 22,
 18,
 18,
 18,
 20,
 21,
 18,
 22,
 18,
 18,
 18,
 18,
 22,
 27,
 27,
 26,
 26,
 26,
 26,
 27,
 27,
 27,
 26,
 26,
 27,
 27,
 27,
 27,
 26,
 26,
 27,
 2,
 27,
 30,
 26,
 12,
 6,
 11,
 8,
 2,
 5,
 7,
 1,
 26,
 15,
 15,
 26,
 26,
 26,
 26,
 26,
 25,
 26,
 27,
 25,
 28,
 28,
 26,
 26,
 27,
 27,
 27,
 26,
 26,
 27,
 26,
 26,
 26,
 26,
 26,
 27,
 0,
 15,
 28,
 11,
 8,
 27,
 29,
 29,
 27,
 25,
 19,
 25,
 12,
 12,
 21,
 13,
 29]

In [271]:
Total = calcular['D01'].sum()

In [272]:
Total

9.210000000000003

In [273]:
mi_serie = calcular.sum(axis=1)

In [180]:
g

MES
1    9.21
Name: D01, dtype: float64

In [195]:
mi_serie

8        2.4500
19       5.0600
28       2.1000
41       2.1000
43       2.3400
53       1.4000
56       1.1000
65       4.5500
88       4.9000
94       8.2500
113      4.3800
117      4.5500
127      1.8100
132      1.6300
158      0.5500
164      3.5000
169      9.3300
179     16.9800
193      5.5500
204      4.5500
224      0.6500
225      1.9500
237      0.6500
253      3.2300
265      5.0500
280      2.8400
292      2.7500
301      3.4200
324      2.9000
333      9.5500
         ...
798      3.7900
810      8.4300
833      2.2400
845      0.9800
856      2.3200
868      0.6730
880      2.9750
891      0.7100
903      1.9000
915      2.6000
926      3.4000
938      1.0000
949      0.6290
965      9.1500
978     10.1700
984      3.4000
995      4.4000
1007     5.8000
1029     1.7321
1041     0.3624
1053     1.3680
1063     1.4744
1069     2.4900
1108    21.1800
1109     6.6000
1115    18.3000
1120    11.9200
1137    19.6900
1155    11.0300
1167     0.4000
Length: 98, dtype: float64

In [194]:
mi_serie.sum()

604.6219

In [197]:
2.45/7

0.35000000000000003

In [198]:
5.06

5.06

In [199]:
2.1/3

0.7000000000000001